### ISSUE TITLE
Not return value selected

### ISSUE THREAD

**Issue by NengChiv** [liamwang/Android-DropdownMenu#1]
I cannot find the way how to get value of dropdownmenu. Please help!

**Comment by liamwang** [comment]
How to make a data item seleted is up to you. 

See:

[https://github.com/liamwang/Android-DropdownMenu/blob/master/app/src/main/java/com/exblr/dropdownmenu/sample/MainActivity.java#L41-L48](https://github.com/liamwang/Android-DropdownMenu/blob/master/app/src/main/java/com/exblr/dropdownmenu/sample/MainActivity.java#L41-L48)

**Comment by NengChiv** [comment]
Thanks
